tests:
  "Tests de non régression":
    path: "/.*"
    assertions:
      - percent(main.memory) < 5% # Contrôle de la consommation de mémoire
      - diff(main.wall_time) < 0.1s # Contrôle du temps de chargement du script